language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sachinrevvsales/multi-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sachinrevvsales/multi-react-test npm test

after_success:
  - docker build -t sachinrevvsales/multi-client ./client
  - docker build -t sachinrevvsales/multi-nginx ./nginx
  - docker build -t sachinrevvsales/multi-server ./server
  - docker build -t sachinrevvsales/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sachinrevvsales/multi-client
  - docker push sachinrevvsales/multi-nginx
  - docker push sachinrevvsales/multi-server
  - docker push sachinrevvsales/multi-worker
