language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sachinrevvsales/multi-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sachinrevvsales/multi-react-test npm test

after_success:
  - docker build -t sachinrevvsales/multi-client ./client
  - docker build -t sachinrevvsales/multi-nginx ./nginx
  - docker build -t sachinrevvsales/multi-server ./server
  - docker build -t sachinrevvsales/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sachinrevvsales/multi-client
  - docker push sachinrevvsales/multi-nginx
  - docker push sachinrevvsales/multi-server
  - docker push sachinrevvsales/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-169835060998"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
